### ISSUE TITLE
Information about Flow

### ISSUE THREAD

**Issue by yodelmas** [dynamicscode/AttachmentManager#2]
Hello !

Firstly, thanks a lot for this one. Muchly appreciated!
Is it possible to have a screenshot about the flow you made ? I can't see it in the doc.

Thanks

**Comment by dynamicscode** [comment]
I have uploaded the Flow in the repository. https://github.com/dynamicscode/AttachmentManager/blob/master/GetSharePointFile_20191016214614.zip
